### ISSUE TITLE
Test geospatial frameworks for PHP and Laravel

### ISSUE THREAD

**Issue by nuest** [TIBHannover/geoMetadata#41]
# Goal

Find out which PHP library is the most promising one to support our requirements and works well with the OJS tooling, e.g., Laravel, and support the required databases (primarily MySQL, secondary: Postgres/PostGIS)

# OJS

OJS supports MySQL `>= 4.1` or PostgreSQL `>= 9.1.5`.

This page gives a good overview of the spatial features in MySQL and MariaDB: https://mariadb.com/kb/en/mysqlmariadb-spatial-support-matrix/

# Libraries

## Candidates for evaluation

- https://github.com/brick/geo
   
  Brick\Geo seems to be pretty powerful (based on GEOS) and has all functions we need; seems well maintained, single maintainer though "brick" looks like a big org, only four contributors though; would require a direct database connection via a PDO; also support for SpatiaLite, so we could also do standalone variant

- Laravel libraries

  - https://github.com/grimzy/laravel-mysql-spatial

    Supports MySQL >= 5.6 and last update ~1 year ago, seems to be (not actively) maintained by individual; yet, _seems to have all features we need_; actually many users but also 14 open PRs, some with seemingly trivial bugfixes, none of the forks is much ahead without being behind, see https://useful-forks.github.io/?repo=grimzy%2Flaravel-mysql-spatial

    See also https://medium.com/@brice_hartmann/getting-started-with-geospatial-data-in-laravel-94502dc74d55 for some quick examples

  - https://github.com/karomap/laravel-geo is the most recent fork of https://github.com/eleven-lab/laravel-geo (via https://useful-forks.github.io/?repo=eleven-lab/laravel-geo) with support for Laravel 5.4+, seems to be maintained by individual, support for MySQL and PostreSQL; documentation at https://karomap.github.io/laravel-geo/

  - https://github.com/mstaack/laravel-postgis
    
    Similar to the above (Laravel migrations etc.), meets all our requirements but for Postgres with PostGIS, 20+ contributors and relatively actively maintained by individual;

## Other

- https://geophp.net/

  No changes since 2016, a fork maintained until mid 2020 seems to be https://github.com/funiq/geoPHP (https://useful-forks.github.io/?repo=phayes%2FgeoPHP), but only low level geometric operations, only Postgres, no MySQL/MariaDB

- https://packagist.org/packages/mjaschen/phpgeo | https://github.com/mjaschen/phpgeo

  Rather low-level geo library, not all required functions; seems well maintained (15 contributors); documentation at https://phpgeo.marcusjaschen.de/

- https://packagist.org/packages/league/geotools

  Looks well-maintained, 30+ contributors, but no polygon overlapping operations;

# Evaluation

## First thoughts

Pro Laravel libraries: we can just integrate with the existing database migration processes, no own schema (hopefully)

Pro brick/geo: Seems to be most well maintained, no need to distinguish between MySQL and other DBMSs, but need own schema then... maybe that's not so hard because we will be the only one

## Tasks

- [ ] re-visit the libraries and check maintenance status
- [ ] create a new database table with a spatial column using each of the candidate libraries
- [ ] insert a `GeometryCollection` of a few points, lines, and polygons into a MySQL database using each of the candidate libraries, from the plugin

**Comment by nuest** [comment]
Closing — `brick/geo` (^0.7.2) is the chosen library and is in `composer.json`. The evaluation matrix in the issue body is decided; a fresh issue can track any future swap.
